package com.Tab.ReportingListeners;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.joda.time.DateTime;
import org.json.JSONObject;

import com.rajatthareja.reportbuilder.Color;
import com.rajatthareja.reportbuilder.ReportBuilder;

 

public class Featurereport
{ 
	
	//masterhtoughts plugin to generate Html base don .json fiel generated by Cucumber
	/*
	 * public static void GenerateSummary() { String RootDir =
	 * System.getProperty("user.dir"); List<String> list = new ArrayList<String>();
	 * list.add("target/cucumber-reports/cucumber.json");
	 * 
	 * String projectName = "Tab Bank";
	 * 
	 * File reportOutputDirectory = new File("target"); List<String> jsonFiles = new
	 * ArrayList<>(); jsonFiles.add("cucumber-report-1.json"); String buildNumber =
	 * "1"; Configuration configuration = new Configuration(reportOutputDirectory,
	 * projectName); // optional configuration - check javadoc for details
	 * configuration.addPresentationModes(PresentationMode.EXPAND_ALL_STEPS);
	 * configuration.setBuildNumber(buildNumber); // addidtional metadata presented
	 * on main page configuration.addClassifications("Platform", "Windows");
	 * configuration.addClassifications("Browser", "chrome");
	 * configuration.addClassifications("Branch", "release/3.8");
	 * 
	 * ReportBuilder reportBuilder = new ReportBuilder(list, configuration);
	 * reportBuilder.generateReports(); }
	 */
	public static void GenerateSummary()
	{
		String path=System.getProperty("user.dir");
		 
ReportBuilder reportBuilder = new ReportBuilder();
        
        // Set output Report Dir 
        reportBuilder.setReportDirectory(path+"\\target\\SummaryReports\\");
        
        // Set output report file name
        reportBuilder.setReportFileName("Summary Report");
        
        // Set Report Title
        reportBuilder.setReportTitle("Automation Execution Report");
        reportBuilder.disableVoiceControl();
        reportBuilder.setAdditionalInfo("Author", "Abhay");
        // Set Report Color for more visit http://materializecss.com/color.html
       
        reportBuilder.setReportColor("light-green lighten-3");
        
        
        // Add additional info for Report
        reportBuilder.setAdditionalInfo("Environment", "QA");

        // Create list or report Files or Directories or URLs or JSONObject or JSONString
        List<Object> cucumberJsonReports = new ArrayList<>();
        cucumberJsonReports.add(new File(path+"\\target\\cucumber-reports\\Cucumber.json"));
      //  cucumberJsonReports.add(new File(path+"\\target\\cucumber-reports\\blue.json"));
        // Build your report
        String newContent =null;
        //Flushing the HTML
        reportBuilder.build(cucumberJsonReports);
        FileReader fr=null;
		try
		{
			File file =new File(path+"\\target\\SummaryReports\\Summary Report.html");
			fr = new FileReader(file); 
		}
		catch (FileNotFoundException e)
		{
		 	e.printStackTrace();
		}
        BufferedReader br= new BufferedReader(fr);
        StringBuilder content=new StringBuilder(1024);
        try
		{
			while((newContent=br.readLine())!=null)
			    {
			    content.append(newContent);
			    }
			 System.out.println(content.toString());
			//Removing Footer
			 newContent=content.toString().replace("<div class=\"container\">            Happy Reporting!            <a class=\"white-text text-lighten-4 right\" href=\"http://reportbuilderjava.rajatthareja.com\">Generated by Report Builder</a>        </div>","");
					}
		catch (IOException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
        try{    
            FileWriter fw=new FileWriter(path+"\\target\\SummaryReports\\Summary Report.html");    
            fw.write(newContent.toString());    
            fw.close();    
           }catch(Exception e){System.out.println(e);}    
           System.out.println("Success...");    
      }    
			          
	
}
